# The Boston Housing Dataset

In [1]:
from sklearn.datasets import load_boston
import numpy as np
import matplotlib.pyplot as plt

In [3]:
boston = load_boston()
type(boston)

sklearn.utils.Bunch

13개의 기준(열)을 가지는 506개의 데이터 셋

In [4]:
x_data = boston.data
print(x_data.shape)

(506, 13)


In [28]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [8]:
# y_data = boston.target
print(y_data.shape)

(506,)


scikit-learn 0.18 버전 이후는 target data Y는 2-dim을 기준으로 받게되었습니다. <br>
따라서 (506,) → (506, 1)로 바꾸어 줍니다.

In [9]:
y_data = boston.target.reshape(boston.target.size, 1)

## 데이터 스케일링

In [10]:
from sklearn import preprocessing

In [15]:
# feature_range 범위에 맞도록 MinMaxScaling을 한다.
minmax_scale = preprocessing.MinMaxScaler(feature_range= (0,5)).fit(x_data)
x_scaled_data = minmax_scale.transform(x_data)

x_scaled_data[:3]

array([[0.00000000e+00, 9.00000000e-01, 3.39076246e-01, 0.00000000e+00,
        1.57407407e+00, 2.88752635e+00, 3.20803296e+00, 1.34601570e+00,
        0.00000000e+00, 1.04007634e+00, 1.43617021e+00, 5.00000000e+00,
        4.48399558e-01],
       [1.17961270e-03, 0.00000000e+00, 1.21151026e+00, 0.00000000e+00,
        8.64197531e-01, 2.73998850e+00, 3.91349125e+00, 1.74480990e+00,
        2.17391304e-01, 5.24809160e-01, 2.76595745e+00, 5.00000000e+00,
        1.02235099e+00],
       [1.17848872e-03, 0.00000000e+00, 1.21151026e+00, 0.00000000e+00,
        8.64197531e-01, 3.47192949e+00, 2.99691040e+00, 1.74480990e+00,
        2.17391304e-01, 5.24809160e-01, 2.76595745e+00, 4.94868627e+00,
        3.17328918e-01]])

In [18]:
x_data[:3]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01,
        6.5750e+00, 6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02,
        1.5300e+01, 3.9690e+02, 4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        7.1850e+00, 6.1100e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9283e+02, 4.0300e+00]])

## Train-Test dataset split

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled_data, y_data, test_size = 0.33)

In [22]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((339, 13), (167, 13), (339, 1), (167, 1))

## Linear Regression Fitting

In [23]:
from sklearn import linear_model

In [24]:
# fit_intercept : w_0 유무
# normalize : L2 Norm 사용
# copy_X : x data를 복사한 후 복사한 값을 분석 시 사용할 지 유무, 일반적으로 복사 후 사용 (True)
# n_jobs : 사용할 CPU 코어 갯수
regr = linear_model.LinearRegression(fit_intercept=True, normalize= True, 
                                     copy_X = True, n_jobs=2)

regr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=2, normalize=True)

boston housing data set에서 weight는 총 13개가 있습니다.

$ y = w_{1}x_{1} + w_{2}x_{2} + ... + w_{13}x_{13} + w_{0}\times 1$

In [26]:
# coefficient
print("Coefficients : ", regr.coef_)
print("intercept : ", regr.intercept_)

Coefficients :  [[-1.65971242  1.23159413  0.29211966  0.66153013 -1.85275679  2.90387753
   0.2013545  -3.47999894  1.29654772 -1.01876849 -1.77799488  0.85065929
  -4.67385144]]
intercept :  [29.02902049]


13개의 Coefficient와 1개의 intercept가 각각의 w에 입력되고 x data가 입력 되었을 때 예측값을 출력합니다.

## 수식 결과 비교

1개의 데이터만 predict 할 때 입력 값들은 matrix 형태로 입력되어야 하므로 reshape을 통하여 1-dim 을 2-dim으로 바꾸어 줍니다.

In [34]:
print(x_test[0])
print(x_test[0].shape)

[0.01122627 1.1        0.98973607 0.         0.47325103 1.94673309
 3.78990731 3.10328365 1.30434783 1.36450382 3.45744681 4.69224368
 1.48592715]
(13,)


In [40]:
print(x_test[0].reshape(-1, 1))
print(x_test[0].reshape(1, -1).shape)

[[0.01122627]
 [1.1       ]
 [0.98973607]
 [0.        ]
 [0.47325103]
 [1.94673309]
 [3.78990731]
 [3.10328365]
 [1.30434783]
 [1.36450382]
 [3.45744681]
 [4.69224368]
 [1.48592715]]
(1, 13)


### regr.predict와 실제 linear 값대로 선형 결합을 해주면 같은 결과가 나옵니다.

In [39]:
regr.predict(x_test[0].reshape(1, -1))

array([[16.59442036]])

In [41]:
x_test[0].dot(regr.coef_.T) + regr.intercept_

array([16.59442036])

In [42]:
regr.predict(x_test[:5])

array([[16.59442036],
       [12.6214814 ],
       [ 2.87665282],
       [26.20816207],
       [15.3510394 ]])

In [43]:
x_test[:5].dot(regr.coef_.T) + regr.intercept_

array([[16.59442036],
       [12.6214814 ],
       [ 2.87665282],
       [26.20816207],
       [15.3510394 ]])

## Metric 측정

In [45]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [46]:
y_pred = regr.predict(x_test)
print("r2_score : ", r2_score(y_true= y_test, y_pred= y_pred))
print("MAE : ", mean_absolute_error(y_true= y_test, y_pred= y_pred))
print("MSE : ", mean_squared_error(y_true= y_test, y_pred= y_pred))

r2_score :  0.7369912902348834
MAE :  3.4174475537144677
MSE :  21.724471896608417
